nightly_audit = """
name: Nightly Audit

on:
  schedule:
    - cron: '0 2 * * *'  # 2 AM UTC daily
  workflow_dispatch:

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Run Nightly Audit
      env:
        API_BASE_URL: https://api.databutton.com/_projects/8fa82f06-8678-43a0-b9a3-2a2a1fe151f5/dbtn/prodx/app/routes
      run: |
        pip install httpx
        python -c "
        import asyncio, httpx
        async def audit():
            async with httpx.AsyncClient(timeout=300) as client:
                r = await client.post('$API_BASE_URL/nightly-audit/run')
                if r.status_code == 200:
                    data = r.json()
                    results = data.get('audit_results', [])
                    critical = [r for r in results if r.get('severity') == 'critical' and r.get('status') == 'fail']
                    if critical:
                        print(f'❌ {len(critical)} critical issues found')
                        exit(1)
                    print(f'✅ Audit passed: {len(results)} checks completed')
                else: exit(1)
        asyncio.run(audit())
        "
"""
